// simp-frontend/src/components/LogIn.jsx
import React, { Component } from 'react'
import UserService from '../services/UserService'
import { withRouter } from '../services/withRouter'

class LogIn extends Component {
    constructor(props) {
        super(props)

        this.state = {
            username: '',
            password: ''
        }
        // this.changeUserameHandler = this.changeUserameHandler.bind(this);
        // this.changePasswordHandler = this.changePasswordHandler.bind(this);

        this.changeUsernameHandler= (event) => {
            this.setState({username: event.target.value});
        }
    
        this.changePasswordHandler= (event) => {
            this.setState({password: event.target.value});
        }
    
        this.handleSubmit = (event) => {
            event.preventDefault();
            const loginDetails = {username: this.state.username, password: this.state.password};
            UserService.authenticate(loginDetails)
            .then((res) =>{
                // console.log(res.data);
                // console.log(res.data.jwtToken);
                // console.log(res.data.user);

                localStorage.setItem("jwtToken", res.data.jwtToken);
                localStorage.setItem("user", JSON.stringify(res.data.user));

                
                const roleName = (JSON.parse(window.localStorage.getItem('user')).role[0].roleName);
                console.log((window.localStorage.getItem('jwtToken')));

                if(roleName==='Admin'){
                    this.props.router.navigate(`/admin/salesmen-list`);
                }
                else{
                    this.props.router.navigate(`/user/allsales`);
                }
            })
            .catch(err => console.log(err))
    
        }
    }

    render() {
        return (
            <div className=" container col-sm-6 offset-md-4 mt-5 mb-2">
                <h2 className="primary"> Login Page </h2>
                <form onSubmit={this.handleSubmit}>

                    <div className="row mb-3">
                        <label className="col-sm-2 col-form-label">Username:</label>
                        <div className="col-sm-4">
                            <input type="text" onChange={this.changeUsernameHandler} className ="form-control" id = "username"  name="username" />
                        </div>
                        
                    </div> 
                    <div className="row mb-3">
                        <label className="col-sm-2 col-form-label">Password:</label>
                        <div className="col-sm-4">
                            <input type="password" onChange={this.changePasswordHandler} className ="form-control" id = "password" name="password" />
                        </div>
                        
                    </div>
                    <button className = "btn btn-primary col-sm-6" type ="submit">Login</button>
        
                </form>
            </div>
        )
    }
}
export default withRouter(LogIn)

// simp-frontend/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { UserAuthService } from '../_service/user-auth.service';
import { UserService } from '../_service/user.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private userService: UserService,
    private userAuthSerivce: UserAuthService,
    private router: Router
  ) { }

  ngOnInit() {
  }

  login(loginForm: NgForm) {
    this.userService.login(loginForm.value).subscribe(
      (response: any)=>{
        this.userAuthSerivce.setRoles(response.user.role);
        this.userAuthSerivce.setToken(response.jwtToken);
        this.userAuthSerivce.setUserId(response.user.userId);
        this.userAuthSerivce.setName(response.user.name);

        const role = response.user.role[0].roleName;
        if(role === 'Admin') {
          this.router.navigate(['/user-list']); //can update later
        } else {
          this.router.navigate(['/']) //update later
        }
      },
      (error)=>{
        console.log(error);
      }
    );
  }

}

<div class="container col-md-6 offset-mid-3">
    <form autocomplete="off" #loginForm="ngForm" (ngSubmit)="login(loginForm)">
        <div class="mb-3">
          <label class="form-label" style="margin-top: 100px;">Username</label>
          <input type="text" name="username" ngModel class="form-control" id="loginUsername" placeholder="Enter your username">
          <div id="emailHelp" class="form-text">Username provided by the library admin.</div>
        </div>
        <div class="mb-3">
          <label class="form-label">Password</label>
          <input type="password" name="password" ngModel class="form-control" id="loginPassword" placeholder="Enter your password">
        </div>
        <input type="submit" value="Login" class="btn btn-primary"/>
    </form>
</div>
